### ISSUE TITLE
You die if you climb many blocks (Creative or /fly)

### ISSUE THREAD

**Issue by UnEnanoMas** [matymare/AntiGenerationWorldScreen#1]
**Dying without reason:**

1.- Get creative or with /fly

2.- Climb many blocks high

3.- Drop you to the ground

**You die instantly for no reason**

(In theory it is impossible to die if you are creative or if you are with / fly since it has anti fall damage)

**Comment by matymare** [comment]
WTF?!

Dne so 4. 7. 2020 15:46 uživatel UnEnanoMas <notifications@github.com>
napsal:

**Comment by UnEnanoMas** [comment]
If you don't believe me, try it yourself

**Comment by matymare** [comment]
I just don't understand what you mean.

Dne so 4. 7. 2020 23:39 uživatel UnEnanoMas <notifications@github.com>
napsal:

**Comment by UnEnanoMas** [comment]
What I mean is that the plugin pretends to remove the protection of not dying from other plugins

If you fly high in creative and you drop you die. If you delete your plugin and do that, you don't die

**Comment by matymare** [comment]
I'll try to fix it, thank you for reporting a bug

Dne ne 5. 7. 2020 0:00 uživatel UnEnanoMas <notifications@github.com>
napsal:

**Comment by matymare** [comment]
I fixed the plugin, thank you for reporting! (Read README.md)

**Comment by UnEnanoMas** [comment]
Thank you for creating it <3
