### ISSUE TITLE
Dont work whit nofalldamage

### ISSUE THREAD

**Issue by UnEnanoMas** [matymare/AntiGenerationWorldScreen#2]
![Captura de pantalla (106)](https://user-images.githubusercontent.com/63286108/86523019-8ffebf00-be66-11ea-9ce6-e761e9de792f.png)

Using: 

**AntiGenerationWorldScreen dev#6**
https://poggit.pmmp.io/ci/Notzide/NoFallDamage/NoFallDamage

(I have switched to another version to see if it worked but not)

![Captura de pantalla (107)](https://user-images.githubusercontent.com/63286108/86523090-86c22200-be67-11ea-84f6-527e0ef8bbce.png)

Using:

**AntiGenerationWorldScreen dev#2**
https://poggit.pmmp.io/ci/Notzide/NoFallDamage/NoFallDamage

**Comment by matymare** [comment]
Hi, you can fix this bug easily by downloading the NoFallDamage plugin.
https://poggit.pmmp.io/p/NoFallDamage

Dne ne 5. 7. 2020 2:32 uživatel UnEnanoMas <notifications@github.com>
napsal:

**Comment by UnEnanoMas** [comment]
Now your plugin doesn't work

![image](https://user-images.githubusercontent.com/63286108/86544415-e8959100-bf26-11ea-8e20-e8f52017ee2c.png)

**Comment by matymare** [comment]
I will try to fix the plugin <3

Dne po 6. 7. 2020 1:21 uživatel UnEnanoMas <notifications@github.com>
napsal:
